---
title: "Evaluación Capstone"
author: "Nicolás Marchant"
date: "2025-12-31"
output: html_document
---

```{r}
# Librerias
library(dplyr)
library(rio)
library(skimr)

# Semilla para reproducibilidad

set.seed(123)

# En la carpeta del capstone descargar "Base Publica ENPG 2024 (Stata 16).dta"
# Cargar base de datos 

ENPG_2024 <- import("Base Publica ENPG 2024 (Stata 16).dta") 

```



```{r}
#exploración de datos

str(ENPG_2024)
head(ENPG_2024)
summary(ENPG_2024)
glimpse(ENPG_2024)

# Limpieza y transformación

ENPG_filtrado <- ENPG_2024 %>% select(RESPONDENT_SERIAL, EDAD, SEXO, OH_1, OH_2, OH_4,
                                      DP_4, DP_5, 
                                      DP_8, DP_12, DP_16, 
                                      MAR_1, MAR_4, PB_1, 
                                      PB_4, COC_1, COC_4, 
                                      TUS_1, TUS_4, T_PR_1_2, T_PR_1_3, 
                                      ST_1, ST_2, ST_5, T_SG_1_B, T_SG_1_E, 
                                      T_SG_1_I, T_SG_1_J, T_SG_1_K, T_SG_1_F, 
                                      CO_1, CO_6, DP_2)


head(ENPG_filtrado)


#Creación variable de consumo (dependiente)

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    alcohol_30d = case_when(
    OH_1 == 2 ~ 0, #NO HA CONSUMIDO ALCOHOL
    OH_4 == 1 ~ 1, #HA CONSUMIDO ULTIMOS 30D
    OH_4 == 2 ~ 0,
    OH_4 == 3 ~ 0)
    )

ENPG_filtrado <- ENPG_filtrado %>% 
mutate (alcohol_30d =case_when(
alcohol_30d == 1 ~ "Sí",
alcohol_30d == 0 ~ "No",
TRUE ~ NA_character_
))

skim(ENPG_filtrado)

table(ENPG_filtrado$alcohol_30d)


```

```{r}

#independientes ()
##1. Folio
ENPG_filtrado <- ENPG_filtrado %>%
rename(Folio = RESPONDENT_SERIAL)

#Sociodemográficas
##2. Edad
ENPG_filtrado <- ENPG_filtrado%>%  
  mutate(edad_recod =case_when(
    EDAD %in% c(12:18)~ 1,
    EDAD %in% c(19:25)~ 2,
    EDAD %in% c(26:34)~ 3,
    EDAD %in% c(35:44)~ 4,
    EDAD %in% c(45:70)~ 5
  )          )

##2.1 Estado civil

ENPG_filtrado <- ENPG_filtrado %>% 
  rename(estado_civil = DP_2)

# 3. Si se encuentra trabajando

ENPG_filtrado <- ENPG_filtrado %>% 
  rename(trabaja_o_no = CO_1, cargo_trabajo = CO_6)

##4. Genero

ENPG_filtrado <- ENPG_filtrado %>%
  mutate(
    genero = case_when(
      SEXO == 1 ~ "Masculino",
      SEXO %in% c(2:6, 99) ~ "Otro género",
      TRUE ~ NA_character_
    ),
    genero = factor(genero),
    genero = relevel(genero, ref = "Otro género")  # <- aquí “inviertes” la referencia
  )
##5. Pertenencia etnica

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(pueblo_ind = case_when(
    DP_4 %in% 1:12 ~ "Indígena",
    DP_4 == 13 ~ "No indígena",
    TRUE ~ NA_character_
  ))


##6. Religión

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(religion = case_when(
    DP_5 %in% 1:11 ~ "Religión",
    DP_5 == 12 ~ "No religión",
    TRUE ~ NA_character_
  ))


##7. Nivel de escolaridad
ENPG_filtrado <- ENPG_filtrado%>%  
  mutate(escolaridad =case_when(
    DP_12 %in% 1:4 ~ "Enseñanza básica o menos",
    DP_12 %in% 5:8 ~ "Enseñanza media",
    DP_12 %in% 9:13~ "Enseñanza superior o más",
    DP_12 %in% 88 ~ "No sabe"
  )          )


ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(educacion_med = case_when(
    DP_12 %in% 5:13 ~ "Sí",
    DP_12 %in% c(1:4, 88) ~ "No", 
    T ~ NA_character_
  ))



##Consumo de otras sustancias

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Consumo_cigarros = case_when(
      ST_2 == 2 ~ 0,
      ST_5 == 1 ~ 1, 
      ST_5 == 2 ~ 0,
      ST_5 == 3 ~ 0
    )
  )

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(Consumo_cigarros = case_when(
    Consumo_cigarros == 1 ~ "Sí",
    Consumo_cigarros == 0 ~ "No",
    TRUE ~ NA_character_
  ))

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Consumo_mar = case_when(
    MAR_1 == 2 ~ 0, #NO HA CONSUMIDO MARIHUANA
    MAR_4 == 1 ~ 1, #HA CONSUMIDO ULTIMOS 30D
    MAR_4 == 2 ~ 0,
    MAR_4 == 3 ~ 0)
    )

ENPG_filtrado <- ENPG_filtrado %>% 
mutate (Consumo_mar =case_when(
Consumo_mar == 1 ~ "Sí",
Consumo_mar == 0 ~ "No",
TRUE ~ NA_character_
))

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Consumo_pb = case_when(
    PB_1 == 2 ~ 0, #NO HA CONSUMIDO PASTA BASE
    PB_4 == 1 ~ 1, #HA CONSUMIDO ULTIMOS 30D
    PB_4 == 2 ~ 0,
    PB_4 == 3 ~ 0)
    )

ENPG_filtrado <- ENPG_filtrado %>% 
mutate (Consumo_pb =case_when(
Consumo_pb == 1 ~ "Sí",
Consumo_pb == 0 ~ "No",
TRUE ~ NA_character_
))

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Consumo_coc = case_when(
    COC_1 == 2 ~ 0, #NO HA CONSUMIDO COCAINA
    COC_4 == 1 ~ 1, #HA CONSUMIDO ULTIMOS 30D
    COC_4 == 2 ~ 0,
    COC_4 == 3 ~ 0)
    )

ENPG_filtrado <- ENPG_filtrado %>% 
mutate (Consumo_coc =case_when(
Consumo_coc == 1 ~ "Sí",
Consumo_coc == 0 ~ "No",
TRUE ~ NA_character_
))

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Consumo_tus = case_when(
    TUS_1 == 2 ~ 0, #NO HA CONSUMIDO TUSI
    TUS_4 == 1 ~ 1, #HA CONSUMIDO ULTIMOS 30D
    TUS_4 == 2 ~ 0,
    TUS_4 == 3 ~ 0)
    )

ENPG_filtrado <- ENPG_filtrado %>% 
mutate (Consumo_tus =case_when(
Consumo_tus == 1 ~ "Sí",
Consumo_tus == 0 ~ "No",
TRUE ~ NA_character_
))


ENPG_filtrado <- ENPG_filtrado %>% 
rename (Riesgo_ocasion = T_PR_1_2,
Riesgo_diario = T_PR_1_3)

ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    Riesgo_ocasion_rec = case_when(
      Riesgo_ocasion == 88 ~ NA_real_,
      TRUE ~ Riesgo_ocasion
    ),
    Riesgo_diario_rec = case_when(
      Riesgo_diario == 88 ~ NA_real_,
      TRUE ~ Riesgo_diario
    )
  )

# Salud 

ENPG_filtrado <- ENPG_filtrado %>% 
  rename(salud_general = ST_1) 


ENPG_filtrado <- ENPG_filtrado %>%  
  mutate(salud_general = case_when(
    salud_general == 88 ~ NA,
    salud_general == 99 ~ NA,
    TRUE ~ salud_general
  ))

ENPG_filtrado <- ENPG_filtrado %>% 
  rename(sm_sueno = T_SG_1_B, sm_agobiado = T_SG_1_E, 
         sm_frustracion = T_SG_1_F, sm_depresion = T_SG_1_I, 
         sm_confianza = T_SG_1_J, sm_valía_moral = T_SG_1_K)

```




```{r}
# Para modelo Logit



ENPG_filtrado <- ENPG_filtrado %>% 
  mutate(
    genero = factor(genero),
    pueblo_ind = factor(pueblo_ind),
    religion = factor(religion),
    educacion_med = factor(educacion_med),
    Consumo_mar = factor(Consumo_mar),
    Consumo_coc = factor(Consumo_coc),
    Consumo_pb = factor(Consumo_pb),
    Consumo_tus = factor(Consumo_tus),
    Consumo_cigarros = factor(Consumo_cigarros),
    EDAD = as.numeric(EDAD),
    Riesgo_diario_rec = factor(Riesgo_diario_rec),
    Riesgo_ocasion_rec = factor(Riesgo_ocasion_rec),
    trabaja_o_no = factor(trabaja_o_no),
    cargo_trabajo = factor(cargo_trabajo),
    salud_general = factor(salud_general),
    estado_civil = factor(estado_civil),
    sm_sueno = as.numeric(sm_sueno),
    sm_agobiado = as.numeric(sm_agobiado),
    sm_depresion = as.numeric(sm_depresion),
    sm_confianza = as.numeric(sm_confianza),
    sm_valía_moral = as.numeric(sm_valía_moral),
    sm_frustracion = as.numeric(sm_frustracion)
    
  )

base_logit <- ENPG_filtrado %>% 
  select(
    alcohol_30d,
    EDAD, genero, pueblo_ind, religion,
    educacion_med,
    Consumo_mar, Consumo_coc, Consumo_pb, Consumo_tus, Riesgo_diario_rec,
    Riesgo_ocasion_rec, sm_sueno, sm_confianza, sm_agobiado, sm_depresion, 
    sm_valía_moral, sm_frustracion, salud_general, estado_civil, 
    Consumo_cigarros, cargo_trabajo, trabaja_o_no
  ) %>% 
  na.omit()

base_logit <- base_logit %>% 
  mutate(
    alcohol_30d = ifelse(alcohol_30d == "Sí", 1,
                          ifelse(alcohol_30d == "No", 0, NA)), 
    EDAD = as.numeric(EDAD), Riesgo_diario_rec = as.numeric(Riesgo_diario_rec), 
    Riesgo_ocasion_rec = as.numeric(Riesgo_ocasion_rec)
  )


modelo_logit <- glm(
  alcohol_30d ~ EDAD + genero + pueblo_ind + religion +
    educacion_med +
    Consumo_mar + Consumo_coc + Consumo_pb + Consumo_tus +
    Riesgo_diario_rec + Riesgo_ocasion_rec + sm_sueno + sm_confianza + sm_agobiado 
  + sm_depresion + sm_valía_moral + sm_frustracion + salud_general + estado_civil + 
    Consumo_cigarros + cargo_trabajo + trabaja_o_no,
  data = base_logit,
  family = binomial(link = "logit"),
  na.action = na.exclude
)

coeficientes <- exp(modelo_logit$coefficients) 
coeficientes

summary(modelo_logit)

table(base_logit$alcohol_30d, useNA = "ifany")
str(base_logit$alcohol_30d)

# Hacer curva Roc y el analisis de sensitividad (con la matriz de confusión) 

```



```{r}
##Random Forest

## Carga de datos

base_rf <- ENPG_filtrado

## preprocesamiento de datos
#Transformar datos a factor previo a su procesamiento como RF

#Variables Folio y Sexo no necesitan tranformación

## 1. Variables que NO se transforman
# Folio y EDAD se mantienen como numéricas / identificadores
str(base_rf$Folio)
str(base_rf$EDAD)

#Variables sociodemográficas categóricas

## Estado civil 

base_rf$estado_civil <- factor(base_rf$estado_civil,
                               levels =  c(1:6), 
                               labels = c("Soltero/a", "Casado/a", 
                                          "Divorciado/a", "Viudo/a", 
                                          "Anulado/a", "Conviviente civil"))

## Sexo (1 = Masculino, 2 = Femenino)
base_rf$SEXO <- factor(base_rf$SEXO,
                       levels = c(1, 2),
                       labels = c("Masculino", "Femenino"))

## Género
base_rf$genero <- factor(base_rf$genero)

## Pueblo indígena
base_rf$pueblo_ind <- factor(base_rf$pueblo_ind)


## Escolaridad (ordenable)
base_rf$educacion_med <- factor(base_rf$educacion_med,
                              ordered = TRUE)
## Religion

base_rf$religion <- factor(base_rf$religion) 
                           

#Variables de consumo

base_rf$Consumo_mar <- factor(base_rf$Consumo_mar,
                              levels = c("No", "Sí"))

base_rf$Consumo_coc <- factor(base_rf$Consumo_coc,
                              levels = c("No", "Sí"))

base_rf$Consumo_cigarros <- factor(base_rf$Consumo_cigarros, 
                                   levels = c("No", "Sí"))

base_rf$Consumo_pb <- factor(base_rf$Consumo_pb,
                             levels = c("No", "Sí"))

base_rf$Consumo_tus <- factor(base_rf$Consumo_tus, 
                              levels = c("No", "Sí"))



##variables de riesgo con factor ordenado

base_rf$Riesgo_ocasion <- factor(base_rf$Riesgo_ocasion,
                                 ordered = TRUE)

base_rf$Riesgo_diario <- factor(base_rf$Riesgo_diario,
                                ordered = TRUE)

##Edad por tramos

base_rf$edad_recod <- factor(base_rf$edad_recod,
                             ordered = TRUE)

# Salud 
base_rf$salud_general <- factor(base_rf$salud_general, 
                                ordered = TRUE)

base_rf$sm_agobiado <- factor(base_rf$sm_agobiado, 
                              ordered = TRUE)

base_rf$sm_confianza <- factor(base_rf$sm_confianza, 
                               ordered = T)

base_rf$sm_depresion <- factor(base_rf$sm_depresion, 
                               ordered = T)

base_rf$sm_frustracion <- factor(base_rf$sm_frustracion, 
                                 ordered = T)

base_rf$sm_sueno <- factor(base_rf$sm_sueno, 
                           ordered = T)

base_rf$sm_valía_moral <- factor(base_rf$sm_valía_moral, 
                                 ordered = T)

# Trabajo 

base_rf$trabaja_o_no <- factor(base_rf$trabaja_o_no, 
                               levels = c(1,2),
                               labels = c("Sí", "No"))

base_rf$cargo_trabajo <- as.numeric(base_rf$cargo_trabajo)


##Revisión de base pre procesada

str(base_rf)
summary(base_rf)


##Selección de variables como predictoras del consumo, usaremos las variables sociodemográficas en esta elección, toda vez que pretendemos conocer las características sociales y demográficas asociadas a la ingesta de alcohol

vars_pred <- c(
  "EDAD",
  "estado_civil",
  "SEXO",
  "genero",
  "pueblo_ind",
  "educacion_med",
  "religion",
  "Consumo_mar",
  "Consumo_coc",
  "Consumo_cigarros",
  "Consumo_pb",
  "Consumo_tus",
  "Riesgo_ocasion",
  "Riesgo_diario",
  "edad_recod",
  "salud_general",
  "sm_agobiado",
  "sm_confianza",
  "sm_depresion",
  "sm_frustracion",
  "sm_valía_moral",
  "trabaja_o_no",
  "cargo_trabajo"
)




## Instalar y cargar paquetes
if(!require(randomForest)) install.packages("randomForest")
if(!require(caret)) install.packages("caret")

library(randomForest)
library(caret)

# Seleccin de columnas
rf_data <- base_rf[, c("alcohol_30d", vars_pred)]

rf_data <- na.omit(rf_data)
# Imputamos valores faltantes

##Para variables categóricas: reemplazamos NA por la categoría más frecuente
for(col in vars_pred){
  if(is.factor(rf_data[[col]])){
    most_common <- levels(rf_data[[col]])[which.max(table(rf_data[[col]]))]
    rf_data[[col]][is.na(rf_data[[col]])] <- most_common
  }
}

## Para variables numéricas: reemplaza NA por la mediana
for(col in vars_pred){
  if(is.numeric(rf_data[[col]])){
    rf_data[[col]][is.na(rf_data[[col]])] <- median(rf_data[[col]], na.rm = TRUE)
  }
}

# Revisión de presencia de NA
sapply(rf_data, function(x) sum(is.na(x)))

# Convertir alcohol_30d en factor
rf_data$alcohol_30d <- factor(rf_data$alcohol_30d, levels = c("No", "Sí"))


# División de datos de entrenamiento y prueba
set.seed(123)
trainIndex <- createDataPartition(rf_data$alcohol_30d, p = 0.7, list = FALSE)

trainData <- rf_data[trainIndex, ]
testData  <- rf_data[-trainIndex, ]

# Construir la fórmula desde vars_pred (variables independientes)
formula_rf <- as.formula(
  paste("alcohol_30d ~", paste(vars_pred, collapse = " + "))
)

# Ajuste del modelo Random Forest
set.seed(123)
rf_model <- randomForest(
  formula_rf,
  data = trainData,
  ntree = 500,
  mtry = floor(sqrt(length(vars_pred))),
  importance = TRUE
)


# Revisar el modelo entrenado
print(rf_model)

#De los resultados obtenidos, se aprecia un error rate de 28.81%, lo que implica que en el 71.19% de las veces
#el modelo predice correctamente el consumo de alcohol en el conjunto de entrenamiento
#Con respecto a la matriz de confusión, el modelo exhibe problemas para predecir los no consumidores, toda vez que presenta un error del 84%;sin embargo, en la predicción de los consumidores de alcohol funciona de mejor forma, con un error del 2.47% aprox. En resumen, el modelo fue capaz de predecir correctamente 8625 casos de consumidores y 664 casos de no consumidores. No obstante, clasificó de forma errónea 3541 casos de no consumidores y 219 casos de consumidores, concluyendo que el modelo resulta más preciso en la identificación de factores asociados al consumo, pero evidencia dificultades en la detección de quienes no consumirán alcohol.


## Predicciones en conjunto de prueba
pred_test <- predict(rf_model, newdata = testData)

# Evaluación del desempeño
confusionMatrix(pred_test, testData$alcohol_30d)


#En complemento a lo señalado precentemente, el modelo en la precisión global acierta en aprox. el 71% de las veces
#Presenta una sensivity del 15%, toda vez que la predicción de los no consumidores no es buena
#Presenta una specifity del 97%, en tanto el modelo predice muy bien a los consumidores



#Importancia de variables 
varImpPlot(rf_model)
importance(rf_model)

#los resultados dan cuenta que, de las variables seleccionadas, las de mayor relevancia para predecir el consumo, estan asociadas a la Edad y el nivel de escolaridad, seguida por sexo y pueblo originario, en el caso de consumidores también adquiere relevancia la pertenencia indígena y se estima que las variables relgión e ingresos no son determinantes en la población objeto de estudio.

#Curva de ROC

# Cargar paquete y librería
if(!require(pROC)) install.packages("pROC")

library(pROC)


# Obtener probabilidades en lugar de clases
pred_probs <- predict(rf_model, testData, type = "prob")

head(pred_probs)


#para la curva de ROC usaremos la probabilidad de clase positiva (si)

prob_si <- pred_probs[, "Sí"]

# Calcular curva ROC
roc_curve <- roc(testData$alcohol_30d, prob_si, levels = c("No", "Sí"), direction = "<")

# Dibujar la curva
plot(roc_curve, main="Curva ROC - Random Forest", col="blue", lwd=2)

coords(roc_curve, treshold = "best")

# Calcular el Área Bajo la Curva (AUC)
auc_value <- auc(roc_curve)
print(paste("Área bajo la curva (AUC):", round(auc_value, 3)))

```



